### ISSUE TITLE
feat: Add auto-release.yml workflow.

### ISSUE THREAD

**Issue by DhruvWebDev** [SolanaCore/pump#18]
Example:
Keep in mind: we need to set the GH_PAT(Github Personal Access Token) secret in the repo so that it has proper rights to make a release
```yml
name: Create GitHub Release

on:
  push:
    tags:
      - 'v*' # triggers on tags like v1.0.0, v2.3.1, etc.

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

```
